# refer to https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: vue-election-app

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage}
  region: ap-southeast-1
  role: ${file(config.js):config.iamrole}
  iamManagedPolicies:
    - ${file(config.js):config.dynamodbpolicy}
    - ${file(config.js):config.cloudwatchlogspolicy}

functions:
  AddItem:
    handler: AddItem.handler
    events:
      - http:
          path: table/additem
          method: post
          cors: true
  AddItems:
    handler: AddItems.handler
    events:
      - http:
          path: table/additems
          method: post
          cors: true
  EditItem:
    handler: EditItem.handler
    events:
      - http:
          path: table/edititem
          method: post
          cors: true
  DeleteItem:
    handler: DeleteItem.handler
    events:
      - http:
          path: table/deleteitem
          method: post
          cors: true
  GetItem:
    handler: GetItem.handler
    events:
      - http:
          path: table/getitem
          method: post
          cors: true
  QueryItems:
    handler: QueryItems.handler
    events:
      - http:
          path: table/queryitems
          method: post
          cors: true
  ScanItems:
    handler: ScanItems.handler
    events:
      - http:
          path: table/scanitems
          method: post
          cors: true

resources:
  AWSTemplateFormatVersion: "2010-09-09"
  Resources:
    ElectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage}-election-tbl
        AttributeDefinitions:
          - AttributeName: electionId
            AttributeType: S
          - AttributeName: creationTimeStamp
            AttributeType: S
          - AttributeName: electionName
            AttributeType: S
#          - AttributeName: startDate
#            AttributeType: S
#          - AttributeName: endDate
#            AttributeType: S
#          - AttributeName: status
#            AttributeType: S
#          - AttributeName: registeredVoters
#            AttributeType: N
#          - AttributeName: totalVotes
#            AttributeType: N
#          - AttributeName: positions
#            AttributeType: S
#          - AttributeName: results
#            AttributeType: M
        KeySchema:
          - AttributeName: electionId
            KeyType: HASH
          - AttributeName: creationTimeStamp
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: "nameLSI"
            KeySchema:
            - AttributeName: electionId
              KeyType: HASH
            - AttributeName: electionName
              KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    CandidatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage}-candidates-tbl
        AttributeDefinitions:
          - AttributeName: electionId
            AttributeType: S
          - AttributeName: positionName
            AttributeType: S
#           - AttributeName: candidateUserId
#             AttributeType: S
#           - AttributeName: voteCount
#             AttributeType: N
        KeySchema:
          - AttributeName: electionId
            KeyType: HASH
          - AttributeName: positionName
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    RegisteredVotersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage}-registered-voters-tbl
        AttributeDefinitions:
          - AttributeName: electionId
            AttributeType: S
          - AttributeName: ballotId
            AttributeType: S
#           - AttributeName: votersUserId
#             AttributeType: S
#           - AttributeName: registrationTimeStamp
#             AttributeType: S
        KeySchema:
          - AttributeName: electionId
            KeyType: HASH
          - AttributeName: ballotId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    VotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage}-votes-tbl
        AttributeDefinitions:
          - AttributeName: electionId
            AttributeType: S
          - AttributeName: submitTimeStamp
            AttributeType: S
#           - AttributeName: positionName
#             AttributeType: S
#           - AttributeName: ballotId
#             AttributeType: S
#           - AttributeName: candidateUserId
#             AttributeType: S
#           - AttributeName: validation
#             AttributeType: S
        KeySchema:
          - AttributeName: electionId
            KeyType: HASH
          - AttributeName: submitTimeStamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
